navs:
  - text: me
    url: "#me"
  - text: work
    url: "#work"
  - text: clients
    url: "#clients"
  - text: skills
    url: "#skills"

navsBack:
  - text: back
    url: "/"

socials:
  - active: true
    icon: linkedin-in
    iconset: fa-sm fab
    name: Linkedin
    url: https://www.linkedin.com/in/robbiebardijn
  - active: true
    icon: twitter
    iconset: fa-sm fab
    name: Twitter
    url: https://twitter.com/robbiebardijn
  - active: true
    icon: github
    iconset: fa-sm fab
    name: Github
    url: https://github.com/rob-bar
