navs:
  -
    text: work
    url: /work
    active: true
  -
    text: skills
    url: /skills
    active: true
  -
    text: blog
    url: /blog
    active: true

socials:
  -
    active : true
    icon: linkedin
    iconset: fab
    name : Linkedin
    url : https://www.linkedin.com/in/robbiebardijn
  -
    active : true
    icon: twitter
    iconset: fab
    name : Twitter
    url : https://twitter.com/robbiebardijn
  -
    active : true
    icon: github
    iconset: fab
    name : Github
    url : https://github.com/rob-bar


projects:
  -
    title : Tetris
    client : "No client, just for fun"
    type : Game
    description : |
      This was a HTML5 game I developed for fun, to spend my time getting to know Javascript and the HTML5 canvas element.To add in a little challenge I wanted to use the Facebook api to let users connect with their Facebook credentials.Everything, from design to the Facebook api to the Javascript was done by me.<br><br>For now the game is off-line.You might want to come back and play it later,I'm optimizing it and puting it with the rest of my games.
    active : true,
    tags :
      - 522081b47c780f78e5ce4a18
      - 522081b47c780f78e5ce4a19
      - 522081b47c780f78e5ce4a16
      - 522081b47c780f78e5ce4a09
      - 522081b47c780f78e5ce4a12
      - Game
    media :
        thumb : own-tetris.jpg"
        big" : "own-tetris.jpg"
        preview : ""
        videos : ""
        pictures : ""
    launch_date : "2012-05-19T22:00:00.000Z"
    likes : 0
  -
    title : Bestnetwork
    client : "Proximus"
    type : SPA
    description : "This project was a very fun one.<br><br>The website was meant to be a teasing website for people who wanted to get to know the Proximus network.For Proximus itself it was important that they could use this website as an entertaining website with some new and fancy things in it.The idea was to work on great content, cartoons, facts and information.So actually it was just a content website, but there was more to it than that.<br><br>The website has a detection build in to serve the mobile or the desktop website based on the browser.the main reason for doing so was the difference between the desktop and the mobile site.As you can see the desktop has a css 3D effect built into (horizontally) and the mobile site has a lazy loading vertical scrolling system.The main reason why we used the m.domain technique instead of going for a responsive website.<br><br>We chose to separate the data with a rest service and to work with Backbone.js on the front-end.This gave us the ability to separate the project better in nicely encapsulated layers.There was another fun feature built in that gave you the ability to control the main menu and items with a remote control (your smartphone).For that we used Socket.io and Node to create rooms between the desktops and the remotes.You should try it out."
    active : true,
    tags :
      - 522081b47c780f78e5ce4a14
      - 522081b47c780f78e5ce4a15
      - 522081b47c780f78e5ce4a08
      - 522081b47c780f78e5ce4a09
      - 522081b47c780f78e5ce4a0a
      - 522081b47c780f78e5ce4a0b
      - 522081b47c780f78e5ce4a0c
      - 522081b47c780f78e5ce4a0e
      - 522081b47c780f78e5ce4a0f
      - 522081b47c780f78e5ce4a18
      - 522081b47c780f78e5ce4a19
      - 522081b47c780f78e5ce4a1a
      - 522081b47c780f78e5ce4a1c
      - SPA
      - 522081b47c780f78e5ce4a1f
    media :
        thumb : "proximus-bestnetwork.jpg"
        big" : "proximus-bestnetwork.jpg"
        preview : "http://www.bestnetwork.be"
        videos : ""
        pictures : ""
    launch_date : "2013-04-21T22:00:00.000Z"
    likes : 0
  -
    title : Asteroids
    client : ""
    type : Game
    description : ""
    active : true
    tags : ""
    media :
        thumb : "own-asteroids.jpg"
        big" : "own-asteroids.jpg"
        preview : ""
        videos : ""
        pictures : ""
    launch_date : "2013-12-11T23:00:00.000Z"
    likes : 0
  -
    title : Polygone Newyear
    client : ""
    type : SPA
    description : ""
    active : true,
    tags : ""
    media :
        thumb : "polygone-newyear.jpg"
        big" : "polygone-newyear.jpg"
        preview : ""
        videos : ""
        pictures : ""
    launch_date : "2013-12-11T23:00:00.000Z"
    likes : 0
  -
    title : Spectre facebook website
    client : "Hp"
    type : SPA
    description : "This was a project that had a huge flow, I think about 20 pages.The project was a teasing website for people who wanted to buy a new laptop.The goal was to let people subscribe for a date with an hp specter laptop.When you registered and filled in the correct answers you could go to one of the resellers stores in your neighborhood to win a brand new Hp spectre.The website itself was build on limonade php and connected with the Facebook SDK.The design was made by Guillaume Janne, slick and beautiful.My goal was to work with fade in fade out animations between the questions,to give it a little touch.The most difficult part, from a technical point of view was the like gate which was integrated somewhere in the middle of the flow which is irregular for Fb applications.I had lots of fun on the project. It allowed me to polish up my Facebook skills."
    active : true,
    tags :
      - 522081b47c780f78e5ce4a14
      - 522081b47c780f78e5ce4a16
      - 522081b47c780f78e5ce4a12
      - 522081b47c780f78e5ce4a18
      - 522081b47c780f78e5ce4a1b
      - 522081b47c780f78e5ce4a09
    media :
        thumb : "hp-spectre.jpg"
        big" : "hp-spectre.jpg"
        preview : ""
        videos : ""
        pictures : ""
    launch_date : "2012-06-11T22:00:00.000Z"
    likes : 0
  -
    title : Viage launch
    client : ""
    type : SPA
    description : ""
    active : true,
    tags : ""
    media :
        thumb : "viage-viage.jpg"
        big" : "viage-viage.jpg"
        preview : ""
        videos : ""
        pictures : ""
    launch_date : "2013-12-11T23:00:00.000Z"
    likes : 0
  -
    title : Stalion BSF
    client : ""
    type : Video
    description : ""
    active : true
    tags : ""
    media :
      thumb : stalion-bsf.jpg"
      big" : "stalion-bsf.jpg"
      preview : ""
      videos : ""
      pictures : ""
    launch_date : "2013-12-11T23:00:00.000Z"
    likes : 0
  -
    title : Drive-E
    client : ""
    type : "Single Page App"
    description : ""
    active : true,
    tags : ""
    media :
      thumb : scansource-drivee.jpg"
      big" : "scansource-drivee.jpg"
      preview : ""
      videos : ""
      pictures : ""
    launch_date : "2013-12-11T23:00:00.000Z"
    likes : 0
  -
    title : Autosalon
    client : ""
    type : SPA
    description : ""
    active : true,
    tags : ""
    media :
        thumb : febiac-autosalon.jpg"
        big" : "febiac-autosalon.jpg"
        preview : ""
        videos : ""
        pictures : ""
    launch_date : "2013-12-11T23:00:00.000Z"
    likes : 0
  -
    title : Canvas Snake
    client : "No client, just for fun"
    type : Game
    description : "I wanted to get the to know the html5 canvas element better.So I build a couple of games in that technology.Canvas snake was one of them, the reason why I chose for snake was because I wanted to make a game that was not to easy to make but also not to difficult.I think I learned a big part of Javascript skills by making the game.The most difficult part was making the body with all the right turns and images, the rest was just good timing and fruit generation.Another thing that was not so simple was the drop shadow on the snake.I'm glad I made this project. Home you enjoy playing the game.Feel free play,share or submit your score."
    active : true,
    tags :
      - Game
      - 522081b47c780f78e5ce4a05
      - 522081b47c780f78e5ce4a16
      - 522081b47c780f78e5ce4a14
      - 522081b47c780f78e5ce4a19
      - 522081b47c780f78e5ce4a18
    media :
        thumb : own-snake.jpg"
        big" : "own-snake.jpg"
        preview : ""
        videos : ""
        pictures : ""
    launch_date : "2012-03-04T23:00:00.000Z"
    likes : 0
  -
    title : Mercedes freemind site
    client : ""
    type : Campaign Website
    description : ""
    active : true
    tags : ""
    media :
      thumb : mercedes-freemind.jpg"
      big" : "mercedes-freemind.jpg"
      preview : ""
      videos : ""
      pictures : ""
    launch_date : "2013-12-11T23:00:00.000Z"
    likes : 0
  -
    title : Rainhunters
    client : ""
    type : "Single Page App"
    description : ""
    active : true
    tags : ""
    media :
      thumb : champion-rainhunters.jpg"
      big" : "champion-rainhunters.jpg"
      preview : ""
      videos : ""
      pictures : ""
    launch_date : "2013-12-11T23:00:00.000Z"
    likes : 0
